// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeAMp7XNWv23y_EjeGJeT8tbbiY7zM_NM',
    appId: '1:159156132366:web:283be144d0c8c4d1ec7a5f',
    messagingSenderId: '159156132366',
    projectId: 'mentairo-12b64',
    authDomain: 'mentairo-12b64.firebaseapp.com',
    storageBucket: 'mentairo-12b64.firebasestorage.app',
    measurementId: 'G-0JMW6EHZ84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoZ9ScNlV2IFgqRyBsSXwl--AS6OCKoKs',
    appId: '1:159156132366:android:403d0e13f92ccf2fec7a5f',
    messagingSenderId: '159156132366',
    projectId: 'mentairo-12b64',
    storageBucket: 'mentairo-12b64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ1PluRD7O24zl1ybiHlpZuVYvNH7ah4U',
    appId: '1:159156132366:ios:cdfc528f71f5d007ec7a5f',
    messagingSenderId: '159156132366',
    projectId: 'mentairo-12b64',
    storageBucket: 'mentairo-12b64.firebasestorage.app',
    iosBundleId: 'com.example.mentairo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeAMp7XNWv23y_EjeGJeT8tbbiY7zM_NM',
    appId: '1:159156132366:web:bb76342cedd56aedec7a5f',
    messagingSenderId: '159156132366',
    projectId: 'mentairo-12b64',
    authDomain: 'mentairo-12b64.firebaseapp.com',
    storageBucket: 'mentairo-12b64.firebasestorage.app',
    measurementId: 'G-2C62DPVT4B',
  );
}
